// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsgvdpxtwplrqwqdiisv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZ3ZkcHh0d3BscnF3cWRpaXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzgwNTksImV4cCI6MjA3MDExNDA1OX0.OxTrzJYI2AV5-B4I3iX23TOeuV0dnJ4yDjW1J1KvLOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});